test: test.c
	gcc test.c -lwiringPi -o test

pseudoSPI: pseudoSPI.c
	gcc pseudoSPI.c -lwiringPi -o pseudoSPI

pseudoSPI_test: pseudoSPI_test.c
	gcc pseudoSPI_test.c -lwiringPi -o pseudoSPI_test

pseudoSPI_speedtest: pseudoSPI_speedtest.c
	gcc pseudoSPI_speedtest.c -lwiringPi -o pseudoSPI_speedtest
